MCU?=atmega328p
ROOT=../../..

include $(ROOT)/vars.mak

FILES := \
  main.o \
  $(ROOT_LIB)/adc/adc.o \
  $(ROOT_LIB)/lowpower/lowpower.o \
  $(ROOT_LIB)/pstr/pstr.o \
  $(ROOT_LIB)/time/measure.o \
  $(ROOT_LIB)/uart/uart.o \

include $(ROOT)/rules.mak