include ../../vars.mak
MCU?=atmega328p

FILES := \
  main.o \
  $(ROOT_LIB)/ina260/ina260.o \
  $(ROOT_LIB)/lowpower/lowpower.o \
  $(ROOT_LIB)/uart/uart.o \
  $(ROOT_LIB)/pstr/pstr.o \
  $(ROOT_LIB)/twi/twi.o

include ../../rules.mak

