include ../../vars.mak

CFLAGS := -DDEBUG

FILES := \
  main.o \
  $(ROOT_LIB)/weather/ms8607.o \
  $(ROOT_LIB)/twi/twi.o \
  $(ROOT_LIB)/uart/uart.o \
  $(ROOT_LIB)/pstr/pstr.o

include ../../rules.mak

